import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { cookies } from "next/headers"
import { decodeJwt } from "./_utility/jwt"

// COMMAND + SHIFT + P (MAC)
// CTRL + SHIFT + P (WINDOWS)
// TODO - Check for the typescript local versoin error for import #3

// Font Variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

// Data about App
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode // <div> <h1> <a> <p> <customComponent>
}>) {
  const cookieStore = await cookies()
  const token = cookieStore.get("authToken")?.value
  const user = token ? decodeJwt(token) : null

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className="min-h-svh flex flex-col ">
          {/* Navigation Bar */}
          <nav className=" flex justify-center p-4">
            <h1>Hello {user?.sub ?? "Guest"}</h1>
          </nav>

          {/* APP */}
          <div className=" bg-gray-900 flex-1">{children}</div>

          {/* Footer */}
          <footer className=" flex justify-center p-4">
            <p>some boring copyright</p>
          </footer>
        </section>
      </body>
    </html>
  )
}
